// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKBi_Wldj5kCycc6o3o0fNlw83oEzFGMk',
    appId: '1:366447619053:web:abe19c44dffe8639add5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    authDomain: 'chat-app-3de74.firebaseapp.com',
    storageBucket: 'chat-app-3de74.appspot.com',
    measurementId: 'G-P0P5XGY4D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQbpxpFwgfXeaS-oTEvORl3KI7ibpeDY',
    appId: '1:366447619053:android:c92f1290ab382ad2add5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    storageBucket: 'chat-app-3de74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_DzaDdFp2VVMWWzf1Cea1-mR2b2i9SY',
    appId: '1:366447619053:ios:c86d97e9ac4eba29add5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    storageBucket: 'chat-app-3de74.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_DzaDdFp2VVMWWzf1Cea1-mR2b2i9SY',
    appId: '1:366447619053:ios:0fdc00c4e0975fc3add5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    storageBucket: 'chat-app-3de74.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
